### PR TITLE
Catching up!

### PR DESCRIPTION
**Pull request by geneb**

### CODE REVIEW

**Comment by geneb** [comment]
On Thu, 8 Oct 2015, wrote:

> Merged #4.
> 
> This is going to sound really dumb, but did the merge move your code to my 
> repo?  I'm still a complete derp when it comes to git. :)

tnx!

g.

## 

Proud owner of F-15C 80-0007
http://www.f15sim.com - The only one of its kind.
http://www.diy-cockpits.org/coll - Go Collimated or Go Home.
Some people collect things for a hobby.  Geeks collect hobbies.

ScarletDME - The red hot Data Management Environment
A Multi-Value database for the masses, not the classes.
http://scarlet.deltasoft.com - Get it _today_!

**Comment by Hertzz58** [comment]
I'm fairly sure that it just moved your commits to the master branch. However, I don't have much experience with this either lol

**Comment by geneb** [comment]
On Thu, 8 Oct 2015, wrote:

> I'm fairly sure that it just moved your commits to the master branch. However, I don't have much experience with this either lol
> 
> Well crap. :)  I hadn't made any changes since the request I'd originally 
> made.  I'm hoping we didn't accidentally break something. :)

g.

## 

Proud owner of F-15C 80-0007
http://www.f15sim.com - The only one of its kind.
http://www.diy-cockpits.org/coll - Go Collimated or Go Home.
Some people collect things for a hobby.  Geeks collect hobbies.

ScarletDME - The red hot Data Management Environment
A Multi-Value database for the masses, not the classes.
http://scarlet.deltasoft.com - Get it _today_!

**Comment by Hertzz58** [comment]
I hope not! It seems as though your fork did get overwritten, I will see if I can revert it and we will go from there!

**Comment by Hertzz58** [comment]
I would open up your local version - if that also wasn't overwritten - and try to re-commit your changes to the branch.

**Comment by geneb** [comment]
On Thu, 8 Oct 2015, wrote:

> I hope not! It seems as though your fork did get overwritten, I will see if I can revert it and we will go from there!
> 
> Well no, I WANTED my fork to get over-written!  I wanted to get all your 
> changes merged back into the fork I'd made. :)

g.


## 

Proud owner of F-15C 80-0007
http://www.f15sim.com - The only one of its kind.
http://www.diy-cockpits.org/coll - Go Collimated or Go Home.
Some people collect things for a hobby.  Geeks collect hobbies.

ScarletDME - The red hot Data Management Environment
A Multi-Value database for the masses, not the classes.
http://scarlet.deltasoft.com - Get it _today_!

**Comment by geneb** [comment]
On Thu, 8 Oct 2015, wrote:

> I would open up your local version - if that also wasn't overwritten - 
> and try to re-commit your changes to the branch.

Well that's just it, I haven't committed anything since the last time we 
synced up a couple of weeks ago.

g.

## 

Proud owner of F-15C 80-0007
http://www.f15sim.com - The only one of its kind.
http://www.diy-cockpits.org/coll - Go Collimated or Go Home.
Some people collect things for a hobby.  Geeks collect hobbies.

ScarletDME - The red hot Data Management Environment
A Multi-Value database for the masses, not the classes.
http://scarlet.deltasoft.com - Get it _today_!

**Comment by Hertzz58** [comment]
Oh, I think that I understand your problem now. I would recommend pulling the latest master branch and then recommit those changes to your fork.

**Pull request merged**
